baseURL = "/"
languageCode = "en-US"
title = "Victoria Ho"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Victoria Ho"
  description = "About Victoria"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "msho10"
  Email         = "hi@vicho.me"
  # Twitter       = "username"
  LinkedIn      = "victoria-ho-a1051524"
  # Stackoverflow = "username"
  # Medium        = "username"
  # Telegram      = "username"
  # RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "certificates"
  weight = 100
  identifier = "certificates"
  url = "/certificates/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "https://resume.vicho.me/"
